### ISSUE TITLE
Add/remove horizontal/vertical lines

### ISSUE THREAD

**Issue by ShashkovS** [ShashkovS/plus_reader#3]
Sometimes there are incorrect table lines (because of row of absolutely accurate pluses or bad quality).
So when you right-click on image a popup with a question appears: 
a) add horizontal line here;
b) add vertical line here;
if there is existing horizontal/vertical line close enough, than
c) remove horizontal line;
d) remove vertical line;

After update 
        self.filled_cells
        self.coords_of_horiz_lns
        self.coords_of_vert_lns
must be correctly reorganized.

**Comment by eyakm1** [comment]
@ShashkovS added in last commit
